# Classic

In [1]:
from pyiron_atomistics import Project

In [2]:
pr = Project("test")

In [3]:
pr.remove_jobs(recursive=True, silently=True)

0it [00:00, ?it/s]

In [4]:
structure = pr.create.structure.ase.bulk("Al", cubic=True)

In [5]:
job = pr.create.job.Lammps("lmp")

In [6]:
job.structure = structure

In [7]:
job.calc_md(pressure=0.0, temperature=500.0, seed=80996)

In [8]:
job.run()

/srv/conda/envs/notebook/lib/python3.13/site-packages/pyiron_atomistics/lammps/base.py:284: UserWarning: No potential set via job.potential - use default potential, 1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1
  warnings.warn(

The job lmp was saved and received the ID: 1

In [9]:
job.decompress()

In [10]:
job["log.lammps"]

/tmp/ipykernel_145/1290020846.py:1: DeprecationWarning: pyiron_base.jobs.job.base.__getitem__ is deprecated: Use job.output for results, job.files to access files; job.content to access HDF storage and job.child_project to access children of master jobs..
  job["log.lammps"]

['LAMMPS (29 Aug 2024)\n',
 'OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)\n',
 '  using 1 OpenMP thread(s) per MPI task\n',
 'units metal\n',
 'dimension 3\n',
 'boundary p p p\n',
 'atom_style atomic\n',
 'read_data structure.inp\n',
 'Reading data file ...\n',
 '  orthogonal box = (0 0 0) to (4.05 4.05 4.05)\n',
 '  1 by 1 by 1 MPI processor grid\n',
 '  reading atoms ...\n',
 '  4 atoms\n',
 '  read_data CPU = 0.001 seconds\n',
 'include potential.inp\n',
 'pair_style eam/alloy\n',
 'pair_coeff * * NiAlH_jea.eam.alloy Ni Al H\n',
 'fix ensemble all npt temp 500.0 500.0 0.1 iso 0.0 0.0 1.0\n',
 'variable dumptime  equal 100\n',
 'variable thermotime  equal 100\n',
 'timestep 0.001\n',
 'velocity all create 1000.0 80996 dist gaussian\n',
 'dump 1 all custom ${dumptime} dump.out id type xsu ysu zsu fx fy fz vx vy vz\n',
 'dump 1 all custom 100 dump.out id type xsu ysu zsu fx fy fz vx vy vz\n',
 'dump_modify 1 sort id format line "%d %d %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g %20.15g"\n',
 'thermo_style custom step temp pe etotal pxx pxy pxz pyy pyz pzz vol\n',
 'thermo_modify format float %20.15g\n',
 'thermo ${thermotime}\n',
 'thermo 100\n',
 'run 1000\n',
 '\n',
 'CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE\n',
 '\n',
 'Your simulation uses code contributions which should be cited:\n',
 '\n',
 '- Type Label Framework: https://doi.org/10.1021/acs.jpcb.3c08419\n',
 '\n',
 '@Article{Gissinger24,\n',
 ' author = {Jacob R. Gissinger, Ilia Nikiforov, Yaser Afshar, Brendon Waters, Moon-ki Choi, Daniel S. Karls, Alexander Stukowski, Wonpil Im, Hendrik Heinz, Axel Kohlmeyer, and Ellad B. Tadmor},\n',
 ' title = {Type Label Framework for Bonded Force Fields in LAMMPS},\n',
 ' journal = {J. Phys. Chem. B},\n',
 ' year =    2024,\n',
 ' volume =  128,\n',
 ' number =  13,\n',
 ' pages =   {3282–-3297}\n',
 '}\n',
 '\n',
 'CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE\n',
 '\n',
 'Neighbor list info ...\n',
 '  update: every = 1 steps, delay = 0 steps, check = yes\n',
 '  max neighbors/atom: 2000, page size: 100000\n',
 '  master list distance cutoff = 7.65\n',
 '  ghost atom cutoff = 7.65\n',
 '  binsize = 3.825, bins = 2 2 2\n',
 '  1 neighbor lists, perpetual/occasional/extra = 1 0 0\n',
 '  (1) pair eam/alloy, perpetual\n',
 '      attributes: half, newton on\n',
 '      pair build: half/bin/atomonly/newton\n',
 '      stencil: half/bin/3d\n',
 '      bin: standard\n',
 'Per MPI rank memory allocation (min/avg/max) = 3.209 | 3.209 | 3.209 Mbytes\n',
 '   Step          Temp          PotEng         TotEng          Pxx            Pxy            Pxz            Pyy            Pyz            Pzz           Volume    \n',
 '         0                  1000    -13.4399999882896    -13.0522195532896     5071.91983667138     1534.68134033888     4189.72125085059     6645.80955957836    -3391.31671357965     6987.53980852988            66.430125\n',
 '       100      435.379402950914    -13.2540261539988    -13.0851945397325    -29708.7929461975     363.440539007576    -5773.80594923001    -22985.7203767784     5920.86969537193    -21809.7604343106     70.8013848352211\n',
 '       200      582.623540719319    -13.1419437821673    -12.9160137721059     8262.93159312091    -1470.78783885891     302.357156216124     5941.85059563895    -11009.0307010265     45081.7648272513     72.1163579638537\n',
 '       300      525.900053472432    -12.8895224156074    -12.6855886641053    -14957.8209148989    -1540.98017907677     21367.0311486667     10997.5935259903    -10548.6619153358     15673.7317538459     75.2028466844922\n',
 '       400      668.488022179882    -13.0447727248861    -12.7855461488529    -28783.8913720336    -1603.18592673392    -12875.3813566925    -1958.60510253076     3772.00618359803    -4232.18968854594     76.8390820646088\n',
 '       500      618.645615597964    -13.2012183822901    -12.9613197163627     3836.29548464762    -976.396492784982     12996.7766127247    -17812.1466267906    -2662.05151202292    -21602.6459195612     73.3270367495672\n',
 '       600      696.481999970556    -13.2415361328307    -12.9714540399125     1141.17368125654     2238.09019008278     3146.49599234319     11895.2515487328     5779.01450823006     10180.6561932851     68.1814955595715\n',
 '       700      285.555721549234    -13.2614628634196    -13.1507299415005    -17484.8897312148     568.777462797345     308.002415793721     735.299394285497    -3941.74942074366     862.086916190585     69.4575590809346\n',
 '       800      158.063704083452    -13.3474464758695    -13.2861524639423    -12312.4900609722     331.550796435633     4454.36027105684    -9746.03072480868    -1974.07036639847    -8879.99328308434     68.6150740475667\n',
 '       900      82.5321783042144    -13.2927270212897    -13.2607226572854     34784.5844840586    -96.4331434446292    -5552.94033844788     40001.0036512224     3350.72332966005     40729.3807082491     64.6435028143388\n',
 '      1000      319.504094363453    -13.3269442766897    -13.2030468399932    -12168.4940146349     781.593501933891     1948.85490258773    -10692.0186682714      -3234.852603078    -12680.6894239928     69.2895070561928\n',
 'Loop time of 0.0204928 on 1 procs for 1000 steps with 4 atoms\n',
 '\n',
 'Performance: 4216.105 ns/day, 0.006 hours/ns, 48797.512 timesteps/s, 195.190 katom-step/s\n',
 '80.8% CPU use with 1 MPI tasks x 1 OpenMP threads\n',
 '\n',
 'MPI task timing breakdown:\n',
 'Section |  min time  |  avg time  |  max time  |%varavg| %total\n',
 '---------------------------------------------------------------\n',
 'Pair    | 0.010214   | 0.010214   | 0.010214   |   0.0 | 49.84\n',
 'Neigh   | 0          | 0          | 0          |   0.0 |  0.00\n',
 'Comm    | 0.0027091  | 0.0027091  | 0.0027091  |   0.0 | 13.22\n',
 'Output  | 0.00075273 | 0.00075273 | 0.00075273 |   0.0 |  3.67\n',
 'Modify  | 0.0061951  | 0.0061951  | 0.0061951  |   0.0 | 30.23\n',
 'Other   |            | 0.0006221  |            |       |  3.04\n',
 '\n',
 'Nlocal:              4 ave           4 max           4 min\n',
 'Histogram: 1 0 0 0 0 0 0 0 0 0\n',
 'Nghost:            360 ave         360 max         360 min\n',
 'Histogram: 1 0 0 0 0 0 0 0 0 0\n',
 'Neighs:            268 ave         268 max         268 min\n',
 'Histogram: 1 0 0 0 0 0 0 0 0 0\n',
 '\n',
 'Total # of neighbors = 268\n',
 'Ave neighs/atom = 67\n',
 'Neighbor list builds = 0\n',
 'Dangerous builds = 0\n',
 'Total wall time: 0:00:00\n']

In [11]:
job["output/generic/temperature"]

/tmp/ipykernel_145/3340484072.py:1: DeprecationWarning: pyiron_base.jobs.job.base.__getitem__ is deprecated: Use job.output for results, job.files to access files; job.content to access HDF storage and job.child_project to access children of master jobs..
  job["output/generic/temperature"]

array([1000.        ,  435.37940295,  582.62354072,  525.90005347,
        668.48802218,  618.6456156 ,  696.48199997,  285.55572155,
        158.06370408,   82.5321783 ,  319.50409436])

# Function

In [12]:
from pyiron_atomistics import pyiron_to_ase

In [13]:
from pyiron_atomistics.lammps.lammps import lammps_function

In [14]:
output = lammps_function(
    working_directory="test_function",
    structure=pyiron_to_ase(structure),
    potential="1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1",
    calc_mode='md',
    calc_kwargs={"pressure": 0.0, "temperature":500.0, "seed":12345},  # some issue with the seed
    cutoff_radius=None,
    units='metal',
    executable_version=None,
    executable_path=None,
    input_control_file=None,
)

In [15]:
output[1]["generic"]["temperature"]

array([1000.        ,  446.27568789,  694.90977856,  474.50744065,
        527.28551136,  696.75148487,  341.39512088,  371.37501195,
        511.99431918,  360.85114921,  728.4821532 ])

# job decorator

In [16]:
from pyiron_base import job as job_decorator

In [17]:
job = job_decorator(lammps_function)(
    working_directory="test_function",
    structure=pyiron_to_ase(structure),
    potential="1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1",
    calc_mode='md',
    calc_kwargs={"pressure": 0.0, "temperature":500.0, "seed":12345},  # some issue with the seed
    cutoff_radius=None,
    units='metal',
    executable_version=None,
    executable_path=None,
    input_control_file=None,
    pyiron_project=pr,
)
job.server.cores

1

In [18]:
job.pull()

The job lammps_function_3ccbd4096461b08b7d4a322173dc81af was saved and received the ID: 2

['LAMMPS (29 Aug 2024)\nOMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)\n  using 1 OpenMP thread(s) per MPI task\nReading data file ...\n  orthogonal box = (0 0 0) to (4.05 4.05 4.05)\n  1 by 1 by 1 MPI processor grid\n  reading atoms ...\n  4 atoms\n  read_data CPU = 0.000 seconds\n\nCITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE\n\nYour simulation uses code contributions which should be cited:\n- Type Label Framework: https://doi.org/10.1021/acs.jpcb.3c08419\nThe log file lists these citations in BibTeX format.\n\nCITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE\n\nNeighbor list info ...\n  update: every = 1 steps, delay = 0 steps, check = yes\n  max neighbors/atom: 2000, page size: 100000\n  master list distance cutoff = 7.65\n  ghost atom cutoff = 7.65\n  binsize = 3.825, bins = 2 2 2\n  1 neighbor lists, perpetual/occasional/extra = 1 0 0\n  (1) pair eam/alloy, perpetual\n      attributes: half, newton on\n      pair build: half/bin/atomonly/newton\n      stencil: half/bin/3d\n      bin: standard\nSetting up Verlet run ...\n  Unit style    : metal\n  Current step  : 0\n  Time step     : 0.001\nPer MPI rank memory allocation (min/avg/max) = 3.209 | 3.209 | 3.209 Mbytes\n   Step          Temp          PotEng         TotEng          Pxx            Pxy            Pxz            Pyy            Pyz            Pzz           Volume    \n         0                  1000    -13.4399999882896    -13.0522195532896     3247.66810715075     3702.83681414109    -2805.58259023778     9650.43612387405    -5696.13397768471     5807.16497375482            66.430125\n       100      446.275687886756    -13.2782494547832    -13.1051924744045    -26715.8155164215    -844.195071879567      1432.7680716075    -26562.5172526597    -1784.75210259988    -23859.2726524295     71.5831336136853\n       200      694.909778558028    -13.1252680184044    -12.8557956021894    -1362.45486824688    -1104.95439219638      2217.3043082447     127.095922295325    -3356.96459167609     9146.04401869458     73.8508038992575\n       300      474.507440649224    -12.8929067106952    -12.7089020089495     17986.3458527134     469.320883344841    -15340.9914283594     69216.0807180621     3346.10023415552    -23937.4116175981     76.4734542037924\n       400      527.285511357426    -12.9585773815022    -12.7541063765388    -32937.2756535844      1250.5946433295     9135.98872434811    -65778.7066592577      -7466.479574514    -41383.0794137525     80.6939419200616\n       500      696.751484873367    -13.1138826534766    -12.8436960595855     15051.4742584912     13755.7952944563     -6540.0334409967     61987.9415294537     10274.1078433073     28217.9994074433     69.9678519293926\n       600      341.395120876788    -13.1738418270364     -13.041455478556     17802.3906532831    -8842.66039501322     859.496551668849     33160.9870825581    -13235.9366284354      21975.302718918     68.4508938052735\n       700      371.375011948674      -13.21075125226    -13.0667392885784    -782.369625241332    -1097.25459637825     370.870487232629    -17849.9909638058     4923.71847944845    -12497.5094891871     72.3655986071596\n       800      511.994319180221    -13.2076222373011    -13.0090808574919     -37079.055493667     2410.40632053089    -3145.79156392548    -14179.5180548924    -11881.7895146534    -1805.95842492327     73.0701001903967\n       900      360.851149207583     -13.027734777858    -12.8878037622481     33957.8871028087    -6490.69310388641    -6126.85141574468     41403.7743154959     18604.4332690867     28485.5155435125     71.1775849647577\n      1000      728.482153201265    -13.1041360531552     -12.821644926897    -12671.3428402397     1742.61518469067    -6409.43441253787     -14770.510185795    -4835.54977273335     12961.8459658764     74.9624816808989\nLoop time of 0.0116892 on 1 procs for 1000 steps with 4 atoms\n\nPerformance: 7391.457 ns/day, 0.003 hours/ns, 85549.266 timesteps/s, 342.197 katom-step/s\n91.7% CPU use with 1 MPI tasks x 1 OpenMP threads\n\nMPI task timing breakdown:\nSection |  min time  |  avg time  |  max time  |%varavg| %total\n---------------------------------------------------------------\nPair    | 0.0061021  | 0.0061021  | 0.0061021  |   0.0 | 52.20\nNeigh   | 0          | 0          | 0          |   0.0 |  0.00\nComm    | 0.0014552  | 0.0014552  | 0.0014552  |   0.0 | 12.45\nOutput  | 0.0004298  | 0.0004298  | 0.0004298  |   0.0 |  3.68\nModify  | 0.0033639  | 0.0033639  | 0.0033639  |   0.0 | 28.78\nOther   |            | 0.0003381  |            |       |  2.89\n\nNlocal:              4 ave           4 max           4 min\nHistogram: 1 0 0 0 0 0 0 0 0 0\nNghost:            360 ave         360 max         360 min\nHistogram: 1 0 0 0 0 0 0 0 0 0\nNeighs:            268 ave         268 max         268 min\nHistogram: 1 0 0 0 0 0 0 0 0 0\n\nTotal # of neighbors = 268\nAve neighs/atom = 67\nNeighbor list builds = 0\nDangerous builds = 0\nTotal wall time: 0:00:00\n',
 {'generic': {'steps': array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000]),
   'natoms': array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]),
   'cells': array([[[4.05000000e+00, 2.47990977e-16, 2.47990977e-16],
           [0.00000000e+00, 4.05000000e+00, 2.47990977e-16],
           [0.00000000e+00, 0.00000000e+00, 4.05000000e+00]],

          [[4.15212324e+00, 2.54244222e-16, 2.54244222e-16],
           [0.00000000e+00, 4.15212324e+00, 2.54244222e-16],
           [0.00000000e+00, 0.00000000e+00, 4.15212324e+00]],

          [[4.19551304e+00, 2.56901081e-16, 2.56901081e-16],
           [0.00000000e+00, 4.19551304e+00, 2.56901081e-16],
           [0.00000000e+00, 0.00000000e+00, 4.19551304e+00]],

          [[4.24460130e+00, 2.59906870e-16, 2.59906870e-16],
           [0.00000000e+00, 4.24460130e+00, 2.59906870e-16],
           [0.00000000e+00, 0.00000000e+00, 4.24460130e+00]],

          [[4.32129230e+00, 2.64602839e-16, 2.64602839e-16],
           [0.00000000e+00, 4.32129230e+00, 2.64602839e-16],
           [0.00000000e+00, 0.00000000e+00, 4.32129230e+00]],

          [[4.12065429e+00, 2.52317304e-16, 2.52317304e-16],
           [0.00000000e+00, 4.12065429e+00, 2.52317304e-16],
           [0.00000000e+00, 0.00000000e+00, 4.12065429e+00]],

          [[4.09065677e+00, 2.50480486e-16, 2.50480486e-16],
           [0.00000000e+00, 4.09065677e+00, 2.50480486e-16],
           [0.00000000e+00, 0.00000000e+00, 4.09065677e+00]],

          [[4.16719720e+00, 2.55167236e-16, 2.55167236e-16],
           [0.00000000e+00, 4.16719720e+00, 2.55167236e-16],
           [0.00000000e+00, 0.00000000e+00, 4.16719720e+00]],

          [[4.18067654e+00, 2.55992607e-16, 2.55992607e-16],
           [0.00000000e+00, 4.18067654e+00, 2.55992607e-16],
           [0.00000000e+00, 0.00000000e+00, 4.18067654e+00]],

          [[4.14426721e+00, 2.53763179e-16, 2.53763179e-16],
           [0.00000000e+00, 4.14426721e+00, 2.53763179e-16],
           [0.00000000e+00, 0.00000000e+00, 4.14426721e+00]],

          [[4.21646001e+00, 2.58183712e-16, 2.58183712e-16],
           [0.00000000e+00, 4.21646001e+00, 2.58183712e-16],
           [0.00000000e+00, 0.00000000e+00, 4.21646001e+00]]]),
   'indices': array([[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]),
   'forces': array([[[-5.55111512e-17, -3.39907768e-33, -3.39907768e-33],
           [ 0.00000000e+00,  8.32667268e-17, -5.55111512e-17],
           [ 5.55111512e-17, -5.55111512e-17, -1.66533454e-16],
           [ 0.00000000e+00, -2.22044605e-16,  2.77555756e-17]],

          [[ 9.07508974e-02,  1.98244126e-02,  3.85928551e-01],
           [ 1.74628101e-02, -1.61617790e-01, -2.08913418e-01],
           [ 2.74154870e-02,  1.52001868e-01, -2.34252338e-01],
           [-1.35629195e-01, -1.02084901e-02,  5.72372051e-02]],

          [[ 3.96810752e-01,  3.47970425e-01, -5.71832361e-01],
           [-4.16742611e-02, -2.71802810e-01,  1.50424846e-01],
           [-2.45512654e-01,  6.45806242e-02,  2.42786778e-01],
           [-1.09623838e-01, -1.40748239e-01,  1.78620736e-01]],

          [[-7.55111489e-01, -4.91942267e-01, -1.58971090e-02],
           [ 6.27230277e-01, -5.12390442e-01, -4.35036085e-02],
           [-4.53109089e-01,  5.85658800e-01,  2.96990902e-01],
           [ 5.80990301e-01,  4.18673908e-01, -2.37590185e-01]],

          [[ 3.26212679e-01, -8.10917881e-02,  3.42793576e-01],
           [-9.36449865e-02,  2.35689205e-02, -1.07184297e-01],
           [-2.77246806e-01, -1.08210792e-01, -4.79098613e-01],
           [ 4.46791131e-02,  1.65733660e-01,  2.43489334e-01]],

          [[ 5.05921792e-01,  5.93803841e-01, -2.46231327e-02],
           [ 5.23181402e-02, -6.79560843e-02, -8.02796639e-02],
           [-1.21651637e-01, -2.57303762e-02,  5.80999968e-01],
           [-4.36588296e-01, -5.00117381e-01, -4.76097171e-01]],

          [[-1.30284397e-01,  2.51112745e-01, -6.16140595e-01],
           [ 3.18824969e-01, -8.03813233e-01,  4.11792767e-01],
           [-2.35623974e-01,  7.34881776e-01,  7.13291593e-02],
           [ 4.70834009e-02, -1.82181288e-01,  1.33018669e-01]],

          [[ 1.23331503e-01,  1.40152753e-01,  3.17577519e-01],
           [-2.86079781e-01,  9.84985257e-02, -1.00737493e-01],
           [ 1.66468909e-01, -6.53056745e-02, -2.89322913e-01],
           [-3.72063123e-03, -1.73345605e-01,  7.24828868e-02]],

          [[ 4.56469833e-02, -2.18237918e-01,  3.15680787e-01],
           [ 4.79446788e-02,  2.91607347e-01, -3.12151972e-01],
           [-4.84794582e-02, -2.81612919e-01, -2.81814220e-03],
           [-4.51122040e-02,  2.08243491e-01, -7.10672954e-04]],

          [[-1.08868544e-02, -8.03991941e-01, -1.03808832e+00],
           [ 1.75176079e-01,  4.70051338e-01,  6.87286163e-01],
           [-3.04571457e-01,  1.93571013e-01,  3.76584874e-01],
           [ 1.40282232e-01,  1.40369590e-01, -2.57827124e-02]],

          [[ 4.87870243e-02,  3.98697354e-01, -1.09887457e-01],
           [-3.74511328e-01, -2.86826692e-01,  4.84249107e-01],
           [ 2.71543337e-03,  1.71983698e-01, -7.97963264e-02],
           [ 3.23008870e-01, -2.83854361e-01, -2.94565324e-01]]]),
   'velocities': array([[[ 5.68799898e-03,  8.20727168e-03, -4.53694213e-03],
           [-3.03317111e-03,  3.09844819e-03, -1.30234767e-03],
           [-8.76953628e-05, -4.60087841e-03, -1.91623030e-03],
           [-2.56713251e-03, -6.70484147e-03,  7.75552010e-03]],

          [[-3.57913233e-03, -3.54433255e-03,  3.65192667e-03],
           [ 4.85250123e-03, -3.91392222e-03, -8.47132489e-04],
           [-2.06425904e-03,  4.97949236e-03,  2.88084558e-04],
           [ 7.90890134e-04,  2.47876241e-03, -3.09287874e-03]],

          [[ 3.84192294e-03,  8.91904806e-04,  3.32248614e-03],
           [-3.95069592e-03,  2.12168049e-03,  1.03200982e-03],
           [ 5.67358904e-03, -1.90164180e-03,  3.63061186e-03],
           [-5.56481606e-03, -1.11194350e-03, -7.98510782e-03]],

          [[ 2.63422707e-03, -5.72476259e-04, -2.19942970e-03],
           [-3.31131357e-03,  7.55351261e-04, -5.93815313e-03],
           [-2.33817951e-03, -2.37016666e-03,  1.36465832e-03],
           [ 3.01526601e-03,  2.18729166e-03,  6.77292451e-03]],

          [[-5.28169522e-03, -1.53306098e-03, -4.48655611e-03],
           [ 5.57387398e-03, -1.93283270e-03,  6.26673651e-03],
           [-7.58203012e-04,  2.57194707e-03, -3.33875275e-03],
           [ 4.66024257e-04,  8.93946602e-04,  1.55857235e-03]],

          [[ 3.77061412e-03,  3.00517334e-03,  1.22596097e-03],
           [-4.22692566e-03,  2.73791599e-03,  5.49876459e-03],
           [ 9.79477296e-04,  2.88194470e-03, -1.58178408e-03],
           [-5.23165758e-04, -8.62503404e-03, -5.14294149e-03]],

          [[-3.54862568e-03,  1.70711245e-03,  9.34626013e-04],
           [ 2.18058400e-03, -2.30835727e-03, -6.51771198e-03],
           [-5.04352262e-04, -1.17492298e-03,  3.75462724e-03],
           [ 1.87239394e-03,  1.77616780e-03,  1.82845872e-03]],

          [[-7.66711489e-04, -5.17327388e-03, -2.16492035e-03],
           [ 5.17309500e-04,  1.20416226e-03,  1.71528223e-03],
           [-4.69101703e-04,  9.83206496e-04, -5.04670321e-03],
           [ 7.18503691e-04,  2.98590512e-03,  5.49634133e-03]],

          [[ 4.48828930e-03,  3.00903486e-03,  2.45507060e-03],
           [-3.48032642e-03, -1.22873611e-04,  3.53040930e-03],
           [ 9.31448440e-04, -3.69092823e-03,  1.76976767e-03],
           [-1.93941132e-03,  8.04766981e-04, -7.75524757e-03]],

          [[-5.46835505e-03,  9.20717013e-04,  7.81753854e-04],
           [ 3.89081127e-03, -1.39704892e-03, -3.32410141e-03],
           [ 2.20190338e-03,  2.66967770e-03,  4.44661040e-03],
           [-6.24359599e-04, -2.19334579e-03, -1.90426284e-03]],

          [[-1.81755323e-03, -2.94583991e-03, -1.97645087e-03],
           [ 2.79947441e-03,  5.80712320e-05, -2.81402171e-03],
           [-3.67418360e-03,  4.56482281e-03, -5.17158400e-03],
           [ 2.69226243e-03, -1.67705414e-03,  9.96205659e-03]]]),
   'unwrapped_positions': array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  2.02500000e+00,  2.02500000e+00],
           [ 2.02500000e+00,  1.23995488e-16,  2.02500000e+00],
           [ 2.02500000e+00,  2.02500000e+00,  2.47990977e-16]],

          [[-5.32705252e-02,  6.57979154e-02, -2.24719683e-01],
           [ 2.58880302e-02,  2.15455086e+00,  2.10345308e+00],
           [ 2.02096562e+00, -9.37593497e-02,  2.13149616e+00],
           [ 2.15854012e+00,  2.02553381e+00,  1.41893684e-01]],

          [[-2.23779417e-01, -2.22079852e-01,  3.49216354e-01],
           [ 1.80951259e-01,  2.02300006e+00,  1.99934470e+00],
           [ 2.18342377e+00,  1.63099396e-01,  2.14757628e+00],
           [ 2.05491744e+00,  2.23149344e+00, -3.00624291e-01]],

          [[ 4.73638694e-01,  1.23208489e-01,  1.53767014e-01],
           [-4.70704125e-01,  2.11397908e+00,  1.76393365e+00],
           [ 2.50392792e+00, -1.48142530e-01,  2.39809541e+00],
           [ 1.73773881e+00,  2.15555626e+00, -7.11947760e-02]],

          [[ 2.09136632e-02,  1.71297904e-02, -2.75256924e-01],
           [ 3.83796276e-03,  1.90196103e+00,  1.90090456e+00],
           [ 2.30872524e+00,  8.31652103e-02,  2.57906976e+00],
           [ 1.98781544e+00,  2.31903627e+00,  1.16574906e-01]],

          [[-1.31584880e-01, -2.31549297e-01, -1.47929853e-01],
           [ 6.92893207e-02,  1.92470778e+00,  2.24740023e+00],
           [ 2.07798659e+00,  1.79340753e-01,  1.79647743e+00],
           [ 2.10496326e+00,  2.24815505e+00,  2.24706482e-01]],

          [[ 1.02638339e-01,  8.26208815e-02,  2.43622604e-01],
           [-1.04719647e-01,  2.22452168e+00,  1.91821479e+00],
           [ 2.08041790e+00, -1.88350121e-01,  2.09897981e+00],
           [ 2.01232017e+00,  1.97186433e+00, -1.70160431e-01]],

          [[-1.57490870e-01, -9.25684070e-02, -2.33105434e-01],
           [ 1.91854870e-01,  2.00166522e+00,  2.01471993e+00],
           [ 1.97315866e+00,  6.70169727e-02,  2.23502693e+00],
           [ 2.15967454e+00,  2.19108342e+00,  1.50555769e-01]],

          [[ 6.61040437e-02, -4.77752826e-02, -2.30391357e-01],
           [-8.12346222e-02,  1.98347648e+00,  2.31520535e+00],
           [ 2.08850124e+00,  1.22616369e-01,  1.92963474e+00],
           [ 2.10730588e+00,  2.12235898e+00,  1.66227813e-01]],

          [[ 1.80177646e-01,  2.09299224e-01,  4.04950050e-01],
           [-1.88176275e-01,  2.02419772e+00,  1.99659393e+00],
           [ 2.26083139e+00, -1.70936330e-01,  2.00280372e+00],
           [ 1.89143445e+00,  2.08170659e+00, -2.60080492e-01]],

          [[-2.15445139e-01, -3.16023555e-01, -9.92183166e-02],
           [ 2.67590952e-01,  2.31127011e+00,  1.91248217e+00],
           [ 2.13614822e+00,  1.91778591e-01,  2.28361856e+00],
           [ 2.02816597e+00,  2.02943486e+00,  1.19577598e-01]]]),
   'positions': array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
           [0.00000000e+00, 2.02500000e+00, 2.02500000e+00],
           [2.02500000e+00, 1.23995488e-16, 2.02500000e+00],
           [2.02500000e+00, 2.02500000e+00, 2.47990977e-16]],

          [[4.09885271e+00, 6.57979154e-02, 3.92740356e+00],
           [2.58880302e-02, 2.15455086e+00, 2.10345308e+00],
           [2.02096562e+00, 4.05836389e+00, 2.13149616e+00],
           [2.15854012e+00, 2.02553381e+00, 1.41893684e-01]],

          [[3.97173363e+00, 3.97343319e+00, 3.49216354e-01],
           [1.80951259e-01, 2.02300006e+00, 1.99934470e+00],
           [2.18342377e+00, 1.63099396e-01, 2.14757628e+00],
           [2.05491744e+00, 2.23149344e+00, 3.89488875e+00]],

          [[4.73638694e-01, 1.23208489e-01, 1.53767014e-01],
           [3.77389717e+00, 2.11397908e+00, 1.76393365e+00],
           [2.50392792e+00, 4.09645877e+00, 2.39809541e+00],
           [1.73773881e+00, 2.15555626e+00, 4.17340652e+00]],

          [[2.09136632e-02, 1.71297904e-02, 4.04603538e+00],
           [3.83796276e-03, 1.90196103e+00, 1.90090456e+00],
           [2.30872524e+00, 8.31652103e-02, 2.57906976e+00],
           [1.98781544e+00, 2.31903627e+00, 1.16574906e-01]],

          [[3.98906941e+00, 3.88910499e+00, 3.97272444e+00],
           [6.92893207e-02, 1.92470778e+00, 2.24740023e+00],
           [2.07798659e+00, 1.79340753e-01, 1.79647743e+00],
           [2.10496326e+00, 2.24815505e+00, 2.24706482e-01]],

          [[1.02638339e-01, 8.26208815e-02, 2.43622604e-01],
           [3.98593712e+00, 2.22452168e+00, 1.91821479e+00],
           [2.08041790e+00, 3.90230665e+00, 2.09897981e+00],
           [2.01232017e+00, 1.97186433e+00, 3.92049634e+00]],

          [[4.00970633e+00, 4.07462880e+00, 3.93409177e+00],
           [1.91854870e-01, 2.00166522e+00, 2.01471993e+00],
           [1.97315866e+00, 6.70169727e-02, 2.23502693e+00],
           [2.15967454e+00, 2.19108342e+00, 1.50555769e-01]],

          [[6.61040437e-02, 4.13290126e+00, 3.95028519e+00],
           [4.09944192e+00, 1.98347648e+00, 2.31520535e+00],
           [2.08850124e+00, 1.22616369e-01, 1.92963474e+00],
           [2.10730588e+00, 2.12235898e+00, 1.66227813e-01]],

          [[1.80177646e-01, 2.09299224e-01, 4.04950050e-01],
           [3.95609093e+00, 2.02419772e+00, 1.99659393e+00],
           [2.26083139e+00, 3.97333088e+00, 2.00280372e+00],
           [1.89143445e+00, 2.08170659e+00, 3.88418672e+00]],

          [[4.00101487e+00, 3.90043645e+00, 4.11724169e+00],
           [2.67590952e-01, 2.31127011e+00, 1.91248217e+00],
           [2.13614822e+00, 1.91778591e-01, 2.28361856e+00],
           [2.02816597e+00, 2.02943486e+00, 1.19577598e-01]]]),
   'temperature': array([1000.        ,  446.27568789,  694.90977856,  474.50744065,
           527.28551136,  696.75148487,  341.39512088,  371.37501195,
           511.99431918,  360.85114921,  728.4821532 ]),
   'energy_pot': array([-13.43999999, -13.27824945, -13.12526802, -12.89290671,
          -12.95857738, -13.11388265, -13.17384183, -13.21075125,
          -13.20762224, -13.02773478, -13.10413605]),
   'energy_tot': array([-13.05221955, -13.10519247, -12.8557956 , -12.70890201,
          -12.75410638, -12.84369606, -13.04145548, -13.06673929,
          -13.00908086, -12.88780376, -12.82164493]),
   'volume': array([66.430125  , 71.58313361, 73.8508039 , 76.4734542 , 80.69394192,
          69.96785193, 68.45089381, 72.36559861, 73.07010019, 71.17758496,
          74.96248168]),
   'pressures': array([[[ 0.32476681,  0.37028368, -0.28055826],
           [ 0.37028368,  0.96504361, -0.5696134 ],
           [-0.28055826, -0.5696134 ,  0.5807165 ]],

          [[-2.67158155, -0.08441951,  0.14327681],
           [-0.08441951, -2.65625173, -0.17847521],
           [ 0.14327681, -0.17847521, -2.38592727]],

          [[-0.13624549, -0.11049544,  0.22173043],

In [19]:
output = job.pull()

In [20]:
output[1]["generic"]["temperature"]

array([1000.        ,  446.27568789,  694.90977856,  474.50744065,
        527.28551136,  696.75148487,  341.39512088,  371.37501195,
        511.99431918,  360.85114921,  728.4821532 ])

In [21]:
df = pr.job_table()
df

,id,status,chemicalformula,job,subjob,projectpath,project,timestart,timestop,totalcputime,computer,hamilton,hamversion,parentid,masterid
0,1,finished,Al4,lmp,/lmp,None,/home/jovyan/test/,2026-04-28 13:47:03.349403,2026-04-28 13:47:05.668512,2.0,pyiron@jupyter-pyiron-dev-pyir-lammps-function-g0os51hv#1,Lammps,0.1,None,None
1,2,finished,None,lammps_function_3ccbd4096461b08b7d4a322173dc81af,/lammps_function_3ccbd4096461b08b7d4a322173dc81af,None,/home/jovyan/test/,2026-04-28 13:47:07.637334,NaT,NaN,pyiron@jupyter-pyiron-dev-pyir-lammps-function-g0os51hv#1,PythonFunctionContainerJob,0.4,None,None

In [22]:
job = pr.load(df[df["job"].str.contains("lammps_function_")]["id"].values[0])

In [23]:
job.output["result"][1]["generic"]["temperature"]

array([1000.        ,  446.27568789,  694.90977856,  474.50744065,
        527.28551136,  696.75148487,  341.39512088,  371.37501195,
        511.99431918,  360.85114921,  728.4821532 ])

# without pyiron_atomitics

In [24]:
from lammpsparser.compatibility.file import lammps_file_interface_function

In [25]:
import os

In [26]:
from ase.build import bulk

In [27]:
shell_output, parsed_output, job_crashed = lammps_file_interface_function(
    working_directory=os.path.abspath("lmp_working_directory"),
    structure=bulk("Al", cubic=True),
    potential="1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1",
    calc_mode="md",
    calc_kwargs={"pressure": 0.0, "temperature":500.0, "seed":12345, "n_ionic_steps": 1000},
    units="metal",
)

In [28]:
parsed_output["generic"]["temperature"]

array([1000.        ,  446.27568789,  694.90977856,  474.50744065,
        527.28551136,  696.75148487,  341.39512088,  371.37501195,
        511.99431918,  360.85114921,  728.4821532 ])

In [29]:
job = job_decorator(lammps_file_interface_function)(
    working_directory=os.path.abspath("lmp_working_directory"),
    structure=bulk("Al", cubic=True),
    potential="1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1",
    calc_mode="md",
    calc_kwargs={"pressure": 0.0, "temperature":500.0, "seed":12345, "n_ionic_steps": 1000},
    units="metal",
    pyiron_project=pr,
)

In [30]:
output = job.pull()

The job lammps_file_interface_function_f9b23105d8f33cca9d7bc247dfae6fc3 was saved and received the ID: 3

In [31]:
df = pr.job_table()
df

,id,status,chemicalformula,job,subjob,projectpath,project,timestart,timestop,totalcputime,computer,hamilton,hamversion,parentid,masterid
0,1,finished,Al4,lmp,/lmp,None,/home/jovyan/test/,2026-04-28 13:47:03.349403,2026-04-28 13:47:05.668512,2.0,pyiron@jupyter-pyiron-dev-pyir-lammps-function-g0os51hv#1,Lammps,0.1,None,None
1,2,finished,None,lammps_function_3ccbd4096461b08b7d4a322173dc81af,/lammps_function_3ccbd4096461b08b7d4a322173dc81af,None,/home/jovyan/test/,2026-04-28 13:47:07.637334,NaT,NaN,pyiron@jupyter-pyiron-dev-pyir-lammps-function-g0os51hv#1,PythonFunctionContainerJob,0.4,None,None
2,3,finished,None,lammps_file_interface_function_f9b23105d8f33cca9d7bc247dfae6fc3,/lammps_file_interface_function_f9b23105d8f33cca9d7bc247dfae6fc3,None,/home/jovyan/test/,2026-04-28 13:47:12.480440,NaT,NaN,pyiron@jupyter-pyiron-dev-pyir-lammps-function-g0os51hv#1,PythonFunctionContainerJob,0.4,None,None

In [32]:
output[1]["generic"]["temperature"]

array([1000.        ,  446.27568789,  694.90977856,  474.50744065,
        527.28551136,  696.75148487,  341.39512088,  371.37501195,
        511.99431918,  360.85114921,  728.4821532 ])

In [33]:
job = pr.load(df[df["job"].str.contains("lammps_file_interface_function_")]["id"].values[0])

In [34]:
job.output["result"][1]["generic"]["temperature"]

array([1000.        ,  446.27568789,  694.90977856,  474.50744065,
        527.28551136,  696.75148487,  341.39512088,  371.37501195,
        511.99431918,  360.85114921,  728.4821532 ])